application:
  bindAddress: :8453
  production: false
  debug: false
database:
  address: localhost:3403
  name: event
  username: tradalia
  password: tradalia
authentication:
  authority: https://tradalia-server:8443/auth/realms/tradalia
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
