application:
  bindAddress: :8453
  production: false
  debug: false
database:
  address: localhost:3403
  name: event
  username: admin
  password: admin
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
messaging:
  address: localhost:8450
  username: admin
  password: admin
